title: 'Solving Climate Change'
author: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1733678833
blueprint: challenge
main_image: 04d26642-9471-434a-acd3-1b9979b4ecdf
intro_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: "One of the most powerful introductions to climate change is David Attenborough's video, linked below. It is as clear about the challenges of Earth's extreme temperatures, massive floods and cataclysmic storms as it is about the many solutions humanity can implement, working together in full cognition of the science, "
  -
    type: paragraph
    content:
      -
        type: text
        text: 'To help enlighten us on those solutions, THI has collected dozens of inspiring editorial pieces from across the continents  --  essays, videos, poetry, music, speeches. We will continue to complement them, as our resources expand, with the most current science and the most persuasive plans of action, such as Project Drawdown.'
featured_content:
  - bf9f3139-9543-45e3-a174-e1910cff4e4f
  - 7a826137-26f5-4603-b372-092516aed2ab
  - 263accbc-caa0-48eb-964e-dccc457c29cc
  - 20f17fae-af70-4c0a-b474-b9a75f95c1b8
  - 239a38c6-1348-452c-b8d1-8136b4dd3c89
  - 9432e426-3382-4116-bcbe-27d3f29aad20
  - 6161f9fc-b922-44da-8c44-f6c1ad2a6a14
title_text: 'Climate-change insights from science, the arts, and policy'
