title: 'Preserving Democracy'
author: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1707617998
blueprint: challenge
main_image: image-1707482190.jpeg
intro_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Intro text for this challenge.'
