title: 'Ending War'
author: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1732483977
blueprint: challenge
main_image: 0442974c-ced8-4ade-b8e9-7f390e1bdfdd
intro_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'War has shaped our history, but what if we could rewrite that narrative? We invite you to step beyond battlefields and explore the intricate threads of peacebuilding.'
featured_content:
  - 12d25b96-227c-4eb6-9b38-f298b55533be
  - bd8e76be-8769-4deb-94d4-3345b5477b38
  - 815f9ddb-8fb2-425d-a7a8-15ec33a0d861
  - e1912d5b-c259-42ca-aa14-01faa3424173
  - 8f635dab-0a70-4f1f-99ac-0f4fe4ab9440
  - 91d3f85d-1560-4132-940f-029c9e3fabfe
title_text: 'Exploring humanity’s quest for lasting peace'
