title: 'Ending War'
author: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1713018613
blueprint: challenge
main_image: tank-man-full-size-2.jpg
intro_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Intro text for this challenge.'
