title: War
author: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1706989927
blueprint: challenge
main_image: stars.mp4
intro_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: kk
