title: 'Africa Foundation'
logo: cropped-af-logo-website-02-300x134.png
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1707842729
blueprint: partner
website: www.africafoundation.org.za
