title: 'Africa Foundation'
logo: cropped-af-logo-website-02-300x134.png
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709083113
blueprint: partner
website: www.africafoundation.org.za
description: |-
  About Africa Foundation’s DNA
  Who we are...
  Founded in 1992, our vision has always been to uplift, up-skill and empower identified rural communities living close to core conservation areas where our partner andBeyond has a footprint. This means we are active in 73 communities across six countries: South Africa, Kenya, Tanzania, Mozambique, Botswana and Namibia.
  We believe that by empowering communities to develop in ways that secure their future welfare, we can contribute to the conservation of Africa’s spectacular natural environment and wildlife. Africa Foundation invests in long term relationships with communities and facilitates the delivery of projects that they identify. Working in collaboration with community members, government and other stakeholders, we ensure that the appropriate structures are in place to guarantee the long term sustainability of any projects developed.