title: '*** Amnesty International  (1961)'
logo: 129327069-45f0fe5f-7fa9-4b09-acbb-3272541534ab-340x144.webp
website: www.amnesty.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710612412
blueprint: partner
description: |-
  In 1946, as the world tried to recover from the trauma of World War II, representatives of the USA, Lebanon and China  --  soon joined by Australia, Chile, France, the Soviet Union and the United Kingdom  --  began to draft a Universal Declaration of Human Rights (UNDHR). 

  Formally adopted by the United Nations General Assembly in December of 1948, it recognizing human rights to be the foundation for freedom, justice and peace. It belongs to all of humanity and forms the basis for international human rights law. It is the most translated document in the world. 

  For the first time, the world had a globally agreed document stating that all humans are free and equal, regardless of sex, colour, creed, religion or other characteristics. Its 30 rights and freedoms include the right to be free from torture, the right to freedom of expression, the right to education and the right to seek asylum. It includes civil and political rights, such as the rights to life, liberty and privacy. It also includes economic, social and cultural rights, such as the rights to social security, health and adequate housing.

  Amnesty International was founded in 1961 to protect this complex set of human rights and has been the leading actor in doing so ever since.