title: '*** Amnesty International'
logo: 129327069-45f0fe5f-7fa9-4b09-acbb-3272541534ab-340x144.webp
website: www.amnesty.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709082221
blueprint: partner
description: |-
  Amnesty International campaigns for a world where human rights are enjoyed by all
  It is a global movement of more than 10 million people in over 150 countries and territories working to end abuses of human rights.