title: '*** Ashoka'
logo: logo.svg
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709756783
blueprint: partner
website: 'https://www.ashoka.org/en-us'
description: |-
  What Ashoka does:

  Ashoka builds and cultivates a community of Fellows, Young Changemakers, Changemaker Institutions, and beyond who see that the world now requires everyone to be a changemaker – a person that sees themselves as capable of creating large-scale, positive change.
   
  Together, amidst the exponential growth of a new inequality in changemaking at a worldwide scale, we mobilize (and accelerate) a movement to build an "Everyone a Changemaker" world where all people have the right and ability to co-lead solutions that transform their societies for the better.