title: 'Ashoka  (1980)'
logo: logo.svg
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727716089
blueprint: partner
website: 'https://www.ashoka.org/en-us/about-ashoka'
description: |-
  In the late 1970's, a young consultant at McKinsey and Company in New York City, began working on a plan to support individuals in the poorest countries of the world  -  common farmers and teachers and housewives who had a good idea for community improvement but lacked the training or financial support to carry it out. Thus, in 1980, Bill Drayton planted the seeds of a humanitarian NGO, named after Ashoka the Great, the enlightened Emperor of Magadha in the Indian subcontinent in the third century BCE. 

  Now, 43 years later, thousands of Ashoka Fellows, young Changemakers, and Changemaker institutions across the planet create and implement powerful ways to improve their communities. They understand deeply that the world in 2024 requires everyone to be a changemaker  --  a person who sees themselves as capable of envisioning large-scale, positive change.
   
  Together, "...amidst the exponential growth of a new inequality in changemaking at a worldwide scale, Ashoka mobilizes (and accelerates) a movement to build an 'Everyone a Changemaker' world  --  where all people have the right and ability to co-lead solutions that transform their societies for the better."