title: '*** Ashoka  (1980)'
logo: logo.svg
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710613608
blueprint: partner
website: 'https://www.ashoka.org/en-us'
description: |-
  In the late 1970's, a young consultant at Mckinsey and Company in New York City, began working on a plan to support individuals in the poorest countries of the world  -  common farmers and teachers and housewives who had a good idea for community improvement but lacked the training or financial support to carry it out.

  Thus the seeds of Ashoka, named after an enlightened Indian emperor of the third century, were planted by Bill Drayton. Now, Ashoka Fellows, young Changemakers, and Changemaker institutions across the planet create and implement powerful ways to improve their communities. They understand that the world in 2024 requires everyone to be a changemaker – a person that sees themselves as capable of creating large-scale, positive change.
   
  Together, amidst the exponential growth of a new inequality in changemaking at a worldwide scale, Ashoka mobilizes (and accelerates) a movement to build an "Everyone a Changemaker" world  --  where all people have the right and ability to co-lead solutions that transform their societies for the better.