title: 'Bangladesh Rural Advancement Committee  (1972)'
logo: image-1709858516.jpeg
website: 'https://brac.net/'
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1711466608
blueprint: partner
description: |-
  In 1970, after the Bhola cyclone claimed half a million lives in Bangladesh, Abed bhai, a senior corporate executive at Pakistan Shell, travelled with friends and colleagues to Monpura, one of the worst-hit regions, to distribute relief. “The death and devastation that I saw happening in my country," he said, "made my life as an executive in an oil company seem very inconsequential and meaningless."

  The 1971 Liberation War in Bangladesh cemented that change in direction for Abed bhai. He resigned from Shell, fled from Pakistan and moved to London, where he helped initiate Action Bangladesh in support of the war.

  Early in 1972, he returned to a newly-independent Bangladesh, finding the country in ruins. The return of 10 million refugees who had sought shelter in India compounded the challenge, demanding urgent relief efforts.  Abed bhai sold his flat in London and used the GBP 16,000 he received from the sale to start work, in the remote region of Sulla in northeastern Bangladesh.

  The Bangladesh Rural Advancement Committee emerged out of the humanitarian response to the crisis with the mission to "...alleviate poverty and encourage economic participation by empowering people through social and economic programs." The Economist describes it as “...the largest, fastest-growing non-governmental organization in the world  --  and one of the most businesslike.”