title: 'Care International'
logo: primary_logo_horizontal_min-1707936023.svg
website: 'https://www.care.org/get-involved/'
description: |-
  What does CARE do? We save lives, defeat poverty, achieve social justice, and fight for women and girls.
  For 78 years, CARE has led the way to a better life for the world’s most vulnerable people. This year, CARE and partners worked in 109 countries, reaching 167 million people through more than 1,600 projects.
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1707948447
blueprint: partner
