title: 'Care International  (1945)'
logo: image-1709838382.jpeg
website: 'https://www.care.org/get-involved/'
description: |-
  This year, CARE and partners worked in 109 countries, implementing more than 1,600 poverty-fighting development and humanitarian aid projects and initiatives that reached 167 million people.

  70.8 million people have been forcibly displaced from their homes. The human consequences of these crises are devastating. Families struggle to find shelter, to get enough to eat, and to find safe places to rebuild their lives. One in five women in crisis has experienced sexual assault.

  On average, humanitarian crises are more complex than at any time in the last 15 years, and last nearly three years longer than they used to. Conflict, migration, and climate change are the key trends driving these crises. These trends to longer, more complicated crises have a huge impact on our ability to support the people in need.

  We need to think about funding over the long term, and not just to fill immediate gaps. We need to think about ways to prepare people and communities to cope with shocks and respond to emergencies themselves. We need to strengthen local institutions that can respond to people on the ground. And we need to find ways to address trends like climate change and conflict that make the situation worse.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713368855
blueprint: partner
