title: 'https://www.bing.com/images/search?view=detailV2&ccid=m5jMK4Lr&id=42322C0FAA02693EE8B8D85A9B7C992C72FDF742&thid=OIP.m5jMK4LrhcDhXsPEASuAUQHaHa&mediaurl=https%3A%2F%2Fwww.ghanayello.com%2Fimg%2Fgh%2Fs%2F1595954027-81-care-international.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.9b98cc2b82eb85c0e15ec3c4012b8051%3Frik%3DQvf9ciyZfJta2A%26pid%3DImgRaw%26r%3D0&exph=600&expw=600&q=logo+for+Care+International&simid=608009976438017273&form=IRPRST&ck=AC5DF5E9DE778E08C3160B97BFA55442&selectedindex=0&itb=1&ajaxhist=0&ajaxserp=0&vt=2Care International'
logo: image-1709838382.jpeg
website: 'https://www.care.org/get-involved/'
description: |-
  CARE works around the globe to save lives, defeat poverty and achieve social justice. We seek a world of hope, inclusion and social justice, where poverty has been overcome and all people live with dignity and security.What does CARE do? We save lives, defeat poverty, achieve social justice, and fight for women and girls.

  For 78 years, CARE has led the way to a better life for the world’s most vulnerable people. This year, CARE and partners worked in 109 countries, reaching 167 million people through more than 1,600 projects.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709838413
blueprint: partner
