title: 'Catholic Relief Services  (1943)'
logo: image-1709838598.jpeg
website: www.crs.org
description: |-
  https://www.youtube.com/watch?v=vgDzHLDbJHM&t=3s

  Mission 

  Catholic Relief Services carries out the commitment of the Bishops of the United States to assist the poor and vulnerable overseas. We are motivated by the Gospel of Jesus Christ to cherish, preserve and uphold the sacredness and dignity of all human life, foster charity and justice, and embody Catholic social and moral teaching as we act to:

  PROMOTE HUMAN DEVELOPMENT by responding to major emergencies, fighting disease and poverty, and nurturing peaceful and just societies; and,

  SERVE CATHOLICS IN THE UNITED STATES as they live their faith in solidarity with their brothers and sisters around the world.

  As part of the universal mission of the Catholic Church, we work with local, national and international Catholic institutions and structures, as well as other organizations, to assist people on the basis of need, not creed, race or nationality.

  Approved by the Catholic Relief Services Board of Directors on September 11, 2008.

  We put our faith into action to help the world’s poorest create lasting change.

  Faith: Faith is our foundation. We have faith in the people we serve and our shared ability to build a more just and peaceful world.

  Action: The desire to serve is not enough. We must act collaboratively to bring about real improvements in peoples’ quality of life and genuine engagement in building peace and justice.

  Results: Demonstrated through measureable outcomes, our actions must be effective in alleviating human suffering, removing root causes and empowering people to achieve their full potential.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709838624
blueprint: partner
