title: 'Catholic Relief Services  (1943)'
logo: image-1709838598.jpeg
website: 'https://www.crs.org'
description: |-
  Catholic Relief Services carries out the commitment of the Bishops of the United States to assist the poor and vulnerable overseas. We are motivated by the Gospel of Jesus Christ to cherish, preserve and uphold the sacredness and dignity of all human life, foster charity and justice, and embody Catholic social and moral teaching. 

  As part of the universal mission of the Catholic Church, we work with local, national and international Catholic institutions and structures, as well as other organizations, to assist people on the basis of need, not creed, race or nationality.

  We put our faith into action to help the world’s poorest create lasting change:

  Faith:  Faith is our foundation. We have faith in the people we serve and our shared ability to build a more just and peaceful world.

  Action:  The desire to serve is not enough. We must act collaboratively to bring about real improvements in peoples’ quality of life and genuine engagement in building peace and justice.

  Results:  Demonstrated through measureable outcomes, our actions must be effective in alleviating human suffering, removing root causes and empowering people to achieve their full potential.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729112
blueprint: partner
