title: 'charity: water  (2006)'
logo: oip.i_qsvmz76swllmp3ggtnsghaha.jpeg
website: 'https://www.charitywater.org/home'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727730678
blueprint: partner
description: 'Since charity: water was founded in 2006, we’ve been chasing one ambitious goal: ending the global water crisis. And while the water crisis is huge, we’re optimistic. We know how to solve the problem, and we make progress every day thanks to the help of local partners and generous supporters. If we work together, we believe everyone will have access to life’s most basic need within our lifetime.'
