title: 'Danish Refugee Council'
logo: unknown-1-1707935013.jpeg
website: 'https://drc.ngo/our-work/what-we-do/core-sectors/'
updated_by: 0800036e-1638-4d6e-822a-26aefe2f9e99
updated_at: 1707948010
blueprint: partner
