title: 'Danish Refugee Council  (1956)'
logo: unknown-1-1707935013.jpeg
website: 'https://drc.ngo/our-work/what-we-do/core-sectors/'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709516527
blueprint: partner
description: |-
  The Danish Refugee Council (DRC) is one of the largest NGOs in the world working with displaced people. They are also one of the top NGOs to work for if you want to work helping people who have been forced to flee their homes due to conflict, disasters or persecution.

  Within the NGO sector, DRC is considered one of the best NGOs to get a job with. They are known for their innovative programmes as well as the scale of their response. With projects focusing on protection, education, economic recovery, peacebuilding, camp coordination and shelter, DRC is one of the leading NGOs in the world. They are also known as one of the highest paying NGOs – another reason why they are one of the best to work for.