title: 'Danish Refugee Council  (1956)'
logo: unknown-1-1707935013.jpeg
website: 'https://drc.ngo/what-we-do/core-sectors/'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1738433707
blueprint: partner
description: |-
  Danish Refugee Council (DRC) (Danish: Dansk Flygtningehjælp) is a private Danish humanitarian nonprofit organization, founded in 1956. It serves as an umbrella organization for 33 member organizations.

  Formed after the Second World War in response to the European refugee crises caused by the Soviet invasion of Hungary in 1956, DRC has been active in large scale humanitarian projects around the world. 

  Through convoy operations, DRC was responsible for delivering half of the international humanitarian aid in Bosnia and Herzegovina during the wars of independence in the former Yugoslavia in the 1990s.

  Today it works in more than 40 countries around the world, with humanitarian programs in conflict zones such as Somalia in the Horn of Africa, Afghanistan in Central Asia, Iraq in the Middle East and Chechnya in the Caucasus.
charity_navigator_rating: 100
