title: 'Danish Refugee Council  (1956)'
logo: unknown-1-1707935013.jpeg
website: 'https://drc.ngo/our-work/what-we-do/core-sectors/'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710001910
blueprint: partner
description: '"DRC Danish Refugee Council works with refugees and internally displaced persons in 40 countries around the world. Our work ranges from emergency aid and reconstruction to assisting refugees in returning home."'
