title: 'Médecins Sans Frontières, aka Doctors Without Borders (1971)'
logo: doctors-without-borders.jpg
website: 'https://www.msf.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729245
blueprint: partner
description: |-
  Médecins Sans Frontières (MSF) was founded in 1971 in Paris by a group of journalists and doctors. Today, it is a worldwide movement of nearly 68,000 people, an international, independent medical humanitarian organisation.

  MSF translates to "Doctors Without Borders." It provides medical assistance to people affected by conflict, epidemics, disasters, or exclusion from healthcare. Their teams are made up of tens of thousands of health professionals, logistic and administrative staff - bound together by a charter, actions guided by medical ethics and the principles of impartiality, independence and neutrality.