title: '*** Doctors Without Borders  (1971)'
logo: doctors-without-borders.jpg
website: www.msf.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709515998
blueprint: partner
description: |-
  An international, independent medical humanitarian organisation

  Médecins Sans Frontières (MSF) translates to Doctors without Borders. We provide medical assistance to people affected by conflict, epidemics, disasters, or exclusion from healthcare. Our teams are made up of tens of thousands of health professionals, logistic and administrative staff - bound together by our charter.  Our actions are guided by medical ethics and the principles of impartiality, independence and neutrality. We are a non-profit, self-governed, member-based organisation.
  MSF was founded in 1971 in Paris by a group of journalists and doctors. Today, we are a worldwide movement of nearly 68,000 people.