title: 'Earth Law Center  (2008)'
logo: image-1707837531.png
website: 'https://www.earthlawcenter.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709859403
blueprint: partner
description: |-
  We Envision a Future in Which Humans and Nature Flourish Together

  Earth Law is the idea that ecosystems have the right to exist, thrive, and evolve—and that Nature should be able to defend its rights in court, just like people can.

  Despite decades of environmental legislation, Earth’s health continues to decline. Because our current laws protect Nature only for the benefit of people and corporations, profit usually takes priority over Nature. Even when environmental issues are brought to court, people must prove that the environmental damage violates their own rights since the environment has no rights of its own.