title: 'Global Citizen  (2008)'
logo: gc-logo-no-space.935935601661-1707851514.png
website: 'https://www.globalcitizen.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713223784
blueprint: partner
description: '"Global Citizens are action takers and impact makers. By working together we are making real progress on achieving the end of extreme poverty for everyone, everywhere."'
