title: 'Human Rights Watch  (1978)'
logo: human-rights-watch-logo.png
website: 'https://www.hrw.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709859472
blueprint: partner
description: |-
  Who We Are

  Human Rights Watch investigates and reports on abuses happening in all corners of the world. We are roughly 550 plus people of 70-plus nationalities who are country experts, lawyers, journalists, and others who work to protect the most at risk, from vulnerable minorities and civilians in wartime, to refugees and children in need. We direct our advocacy towards governments, armed groups and businesses, pushing them to change or enforce their laws, policies and practices. To ensure our independence, we refuse government funding and carefully review all donations to ensure that they are consistent with our policies, mission, and values. We partner with organizations large and small across the globe to protect embattled activists and to help hold abusers to account and bring justice to victims.