title: 'International Rescue Committee  (1933)'
logo: image-1709835889.png
website: 'https://www.rescue.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727730627
blueprint: partner
description: |-
  Founded at the call of Albert Einstein in 1933, the IRC is at work in over 50 crisis-affected countries throughout Europe and the Americas. We deliver lasting impact by providing health care, helping children learn, and empowering individuals and communities to become self-reliant, always seeking to address the inequalities facing women and girls.

  In 2022, the IRC and our partners reached over 32.9 million people in countries affected by crisis. Our teams work around the clock to ensure families can survive, recover and regain control of their futures. 

  The IRC compiles an annual list of the 20 humanitarian crises expected to deteriorate the most over the next year. For the past decade, this report has helped us determine where to focus our emergency services and lifesaving support to make the greatest impact.