title: '*** International Rescue Committee  (1933)'
logo: image-1709835889.png
website: www.rescue.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709835904
blueprint: partner
description: |-
  The IRC's impact at a glance
  The International Rescue Committee (IRC) helps people affected by humanitarian crises—including the climate crisis—to survive, recover and rebuild their lives.

  Our work
  Founded at the call of Albert Einstein in 1933, the IRC is now at work in over 50 crisis-affected countries as well as communities throughout Europe and the Americas. We deliver lasting impact by providing health care, helping children learn, and empowering individuals and communities to become self-reliant, always seeking to address the inequalities facing women and girls.

  Here are highlights of our impact over a year.

  32.9 million+

  people in countries affected by crisis were reached by the IRC and partners in 2022
  Our teams work around the clock to ensure families can survive, recover and regain control of their futures.
  See 5 ways we make a difference.
  In 2022, the IRC and our partners reached over 32.9 million people in countries affected by crisis. As part of this work, we:

  Supported 3,137 health facilities
  Provided 8,013,515 primary health care consultations
  Treated 222,278 children under 5 for severe acute malnutrition
  Admitted 453,344 children and 106,722 pregnant and lactating women to nutrition programs
  Built or rehabilitated water supplies serving 3,490,159 people
  Reached 1,421,270 people with cash assistance
  Distributed $109,751,532 in cash or vouchers
  Provided counseling to 43,814 women survivors of gender-based violence
  Supported 122,390 children in IRC safe spaces and other protection programs
  Enrolled 807,853 children and youth in learning programs
  Provided 186,491 individuals with livelihood support
  ... among other assistance provided around the world last year.