title: '*** International Rescue Committee  (1933)'
logo: image-1709835889.png
website: www.rescue.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710620332
blueprint: partner
description: |-
  Founded at the call of Albert Einstein in 1933, the IRC is now at work in over 50 crisis-affected countries as well as communities throughout Europe and the Americas. "We deliver lasting impact by providing health care, helping children learn, and empowering individuals and communities to become self-reliant, always seeking to address the inequalities facing women and girls."

  1933

  American branch of the European-based International Relief Association (IRA) is founded at the suggestion of Albert Einstein to assist Germans suffering under Hitler. Refugees from Mussolini's Italy and Franco's Spain are later assisted.

  1940

  Emergency Rescue Committee (ERC) formed to support European refugees trapped in Vichy France. Over 2,000 political, cultural, union and academic leaders rescued in 13 months.

  1942

  IRA and ERC join forces under the name International Relief and Rescue Committee, later shortened to the International Rescue Committee.

  1945

  The IRC, at the end of World War II, initiates emergency relief programs, establishes hospitals and children's centers and starts refugee resettlement efforts in Europe. With the descent of the Iron Curtain in 1946, the IRC initiates resettlement program for East European refugees, which continues until the end of the Cold War.