title: 'International Volunteers for Peace  (1982)'
logo: logo-1.png
website: 'https://www.ivp.org.au'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710367998
blueprint: partner
description: |-
  What We Do

  International Volunteers for Peace (IVP), in collaboration with its partners, organises volunteer projects in communities across the globe. We recruit participants from Australia and other countries through our global network.

  IVP is a Branch of Service Civil International (SCI), an international non-governmental voluntary service organisation with Branches in 44 countries and 106 Partners and Contacts in Africa, Asia, Europe and the Americas. 

  In 1987, SCI received the title of “Messenger of peace” from the General Secretary of the United Nations in recognition of SCI’s efforts to promote peace and international understanding and for activities developed during the International Year of Peace in 1985.

  IVP is a member of Network for Voluntary Development in Asia (NVDA), which is a network of international voluntary service (IVS) NGOs in Asia & Oceania. NVDA was founded in 1997 and now has 30 member NGOs in 20 countries/area. NVDA organized 1,949 IVS projects and exchanged 14,155 vols. in 2015. NDVA started IVS projects in 17 new countries and actively work for environmental or social common actions, development in PR (Public Relations) and LMTV (Long and Middle Term Voluntary service), impact research, etc.

  IVP involved Projects are initiated and organised by community groups, and are designed to be of tangible benefit to the local community. They enhance local initiatives and do not replace paid labour. Our projects historically have been described as ‘work camps’. Using this model, we bring together people of diverse race, ideology, nationality and age who live together while working on a community project. We offer short-term, and medium to long-term projects.

  The Constitution of IVP can be downloaded here.

  Please note: IVP is a membership-based organisation. To be accepted on one of our workcamp projects you must become a member.