title: '*** International Rescue Committee  (1933)'
logo: image-1709835889.png
website: www.rescue.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710619798
blueprint: partner
description: 'Founded at the call of Albert Einstein in 1933, the IRC is now at work in over 50 crisis-affected countries as well as communities throughout Europe and the Americas. We deliver lasting impact by providing health care, helping children learn, and empowering individuals and communities to become self-reliant, always seeking to address the inequalities facing women and girls.'
