title: 'Karuna Center for Peacebuilding'
logo: kcp-web-logo-hz-162h.png
website: 'https://karunacenter.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709085139
blueprint: partner
description: |-
  OUR MISSION
  To empower people divided by conflict to develop mutual understanding and to create sustainable peace.
  WE ENVISION
  A just and peaceful world in which difference is a source of creativity and strength.