title: 'Oxfam International  (1942)'
logo: image-1709838711.jpeg
website: www.oxfam.org
description: |-
  "Oxfam is a global organization that fights inequality to end poverty and injustice. We offer lifesaving support in times of crisis and advocate for economic justice, gender equality, and climate action. We demand equal rights and equal treatment so that everyone can thrive, not just survive. The future is equal.

  "Inequality is the most pressing issue of our time. And for 80 years, people like you have fueled our mission to end poverty and injustice. From the highlands of Central America and the corn fields of Uganda to the shores of the southern Gulf Coast in the US, Oxfam and our supporters are fighting to guarantee a life of dignity for every person in crisis and to challenge billionaires, corporations, governments, and international financial institutions to do better."
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1711309110
blueprint: partner
