title: 'Parvati Foundation  (2014)'
logo: pf-stacked-logo-navy-1707948866.svg
website: 'https://parvati.org/'
description: |-
  "Parvati Foundation is an all-volunteer international non-profit organization working to create a peaceful, prosperous, healthy world by helping everyone remember our inherent interconnection.

  "Having started in Canada to end the threat of seismic testing in Canada’s Arctic Ocean, we now have representation in 40 countries, dedicated to the creation of the world’s largest protected area and supporting the global mindset that will sustain it.

  "Our shared voice includes heads of state, renowned advisors, and subject matter experts from a wide range of fields including scientific, economic, technological, artistic, and media, next-generation inheritors, and everyday citizens.

  "We are not okay that people and nature everywhere are suffering right now, from the effects of greed, apathy, imbalance, and violence.

  "And we are using compassion, advocacy, grassroots education and global multimedia strategy to ensure that urgently needed change is implemented at the speed and scale required for today’s collective crises."

  https://parvati.org/sign-the-maps-petition/
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713223862
blueprint: partner
