title: 'Peace Direct  (2003)'
logo: logo-1707838315.svg
website: www.peacedirect.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709859777
blueprint: partner
description: |-
  OUR WORK & PARTNERS
  Local voices and approaches are at the heart of everything we do. When it comes to peacebuilding projects, we are led by local peacebuilders, groups and organisations. We do everything we can to support our partners, including funding, knowledge-sharing, networking and beyond. We also raise global awareness about locally-led peacebuilding and garner for international support.