title: 'Peace Direct  (2003)'
logo: image-1710054732.jpeg
website: 'https://www.peacedirect.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727730524
blueprint: partner
description: |-
  "Peace Direct is an international charity dedicated to stopping violence. We partner with local people to end conflicts and build sustainable peace. 

  "Local voices and approaches are at the heart of everything we do. When it comes to peacebuilding projects, we are led by local peacebuilders, groups and organisations. We do everything we can to support our partners, including funding, knowledge-sharing, networking and beyond. We also raise global awareness about locally-led peacebuilding and garner for international support. 

  We work towards a world where local communities can sustain peace themselves, without external support. That means we support peacebuilding work that helps develop livelihood opportunities that ensure they can’t be taken advantage of by armed groups. And, in the long-term, it means we are working towards a reality where the peacebuilders we currently work with do not have to rely on support from intermediary organisations like us, or even international funders, to access the resources they need.