title: 'Project Drawdown'
logo: projectdrawdown_logo.png
website: www.drawdown.org
description: |-
  "Project Drawdown is the world’s leading resource for climate solutions.

  "Our mission is to help the world stop climate change—as quickly, safely, and equitably as possible. 

  "To do this, we pursue three key strategies:

  "Advance Effective, Science-based Climate Solutions and Strategies. We do the science no one else does to cut through the noise and find effective “whole system” solutions and strategies for stopping climate change.

  "Foster Bold, New Climate Leadership. We inform, inspire, and empower business leaders, investors, and philanthropists to take bold, new positions, act more strategically, and rapidly bring climate solutions to scale.

  "Promote New Narratives and New Voices. We work to shift the conversation about climate change from 'doom and gloom' to "possibility and opportunity.' And we elevate new, underrepresented climate heroes through storytelling and 'passing the mic.'"
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1710104727
blueprint: partner
