title: 'Protect Democracy'
logo: image-1713224652.png
website: 'https://protectdemocracy.org'
description: |-
  It’s not just the United States. With few exceptions, democracies are struggling everywhere.

  THE THREAT TO DEMOCRACY

  Global freedom is threatened not just by rising autocracies, but also by major democracies faltering from within. This graph shows the relative change in quality of democracy in key countries since 2011.

  As a result, four out of every five people globally live in countries becoming less democratic.
  Past decades’ progress towards democracy has stalled and then reversed. Today, a larger percent of the world lives under an autocratic government than when the Berlin Wall went up.
  V-Dem Institute Liberal Democracy Index, 2021

  Why are democracies reeling?

  Experts have various explanations for why democracy is suddenly receding around the world, all at once. Theories range from technological change and global economic shifts to growing social atomization and backlash to demographic changes.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713224814
blueprint: partner
