title: 'Rainforest Action Network  (1985)'
logo: image-1709838812.jpeg
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727730315
blueprint: partner
website: 'https://www.ran.org'
description: |-
  MISSION
  Rainforest Action Network (RAN) preserves forests, protects the climate and upholds human rights by challenging corporate power and systemic injustice through frontline partnerships and strategic campaigns.

  VISION
  RAN works toward a world where the rights and dignity of all communities are respected and where healthy forests, a stable climate and wild biodiversity are protected and celebrated.

  VALUES: FIGHTING FOR PEOPLE AND PLANET
  We are committed to doing what is necessary, not only what is considered politically feasible, to preserve rainforests, protect the climate, and uphold human rights.