title: 'Refugees International'
logo: sm_logo_blue1.jpg
website: 'https://www.refugeesinternational.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709490183
blueprint: partner
description: 'Refugees International advocates for lifesaving assistance, human rights, and protection for displaced people and promotes solutions to displacement crises.'
