title: 'Refugees International  (1979)'
logo: image-1709838894.jpeg
website: 'https://www.refugeesinternational.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713373397
blueprint: partner
description: |-
  Refugees International was started in 1979 as a citizens’ movement to defend the rights of people fleeing Vietnam, Cambodia, and Laos. Since then, we have expanded to become a globally focused organization, advocating wherever rights and refuge are at risk.

  Today, an unprecedented number of people globally have been forced to flee conflict, crisis, and climate impacts at home. As these challenges increasingly collide, international systems designed to protect and aid people in need have not kept up, and the rise of exclusionary politics have eroded access to refuge. We know that a better world is possible. Refugees International is here to fight for rights and refuge for all.

  Our experts work with partners around the world to investigate the challenges displaced people face, develop policy solutions, mobilize action, and hold the powerful to account.

  Refugees International believes that people experiencing displacement must be at the center of the movement to advance solutions. We are dedicated to expanding the space for refugee and local leadership in our organization, in the public square, and in the halls of power.