title: '*** Rotary International'
logo: image-1709164813.jpeg
website: www.rotary.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709237244
blueprint: partner
description: |-
  Rotary is a global network of 1.4 million neighbors, friends, leaders, and problem-solvers who see a world where people unite and take action to create lasting change – across the globe, in our communities, and in ourselves.

  Solving real problems takes real commitment and vision. For more than 110 years, Rotary's people of action have used their passion, energy, and intelligence to take action on sustainable projects. From literacy and peace to water and health, we are always working to better our world, and we stay committed to the end.

  Learn more about our structure and our foundation and our strategic vision.

  What we do

  Rotary members believe that we have a shared responsibility to take action on our world’s most persistent issues. Our 46,000+ clubs work together to:

  Promote peace
  Fight disease
  Provide clean water, sanitation, and hygiene
  Save mothers and children
  Support education
  Grow local economies
  Protect the environment
  Get involved

  Our mission

  We provide service to others, promote integrity, and advance world understanding, goodwill, and peace through our fellowship of business, professional, and community leaders.

  Vision statement

  Together, we see a world where people unite and take action to create lasting change — across the globe, in our communities, and in ourselves.