title: 'Save the Children  (1919)'
logo: image-1709837479.png
website: 'https://www.savethechildren.org'
description: |-
  "Our Work Around the World

  "Every child deserves a healthy start in life, the opportunity to learn and protection from harm. Yet, an estimated 5.4 million children under age 5 still die each year from preventable causes; 250 million children around the world can’t read, despite years of schooling; and far too many are experiencing physical and emotional abuse, sexual exploitation, deprivation and neglect. 

  "That's why  --   as global leaders in child health, education and protection  --  we're working in more than 100 countries to change the lives of over 100 million children every year."
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1711237346
blueprint: partner
