title: 'Search for Common Ground'
logo: image-1709838987.jpeg
website: 'https://www.sfcg.org/'
description: |-
  "For over 40 years, Search for Common Ground has been building trust around the world, opening opportunities for collaboration between communities, and creating breakthroughs for peace. 

  "Our ability to deal with conflict affects how we handle every issue humanity is facing. Whether global in nature, such as poverty, hunger or the environment, or closer to home, such as family or community relations, we face daily challenges to our abilities to deal with conflict constructively.

  "Without peace, development gains do not hold. Without peace, delivering humanitarian aid risks further suffering. Without peace, people have more difficulty exercising agency, seizing opportunity, and realizing their full potential. Peace enables trust and provides the foundation for collaboration to solve complex problems. It allows people to look past differences, have difficult conversations, take shared risks, find common ground, and invest in pathways towards a shared future."
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709838999
blueprint: partner
