title: 'The Nuclear Age Peace Foundation  (1982)'
logo: logo-square-pdf-2022-jpg.jpeg
website: 'https://wagepeace.org/index.html'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729951
blueprint: partner
description: |-
  NUCLEAR WEAPONS HAVE NO PLACE IN THIS WORLD

  Since 1982, The Nuclear Age Peace Foundation has worked to create a
  just and peaceful world, free of nuclear weapons.

  We work on advancing the Treaty on the Prohibition of Nuclear Weapons and other nuclear disarmament, nuclear justice, and peace initiatives. 

  We are a non-profit, non-partisan 501(c)(3), with consultative status to the United Nations
  Economic and Social Council, recognized by the UN as a Peace Messenger Organization.