title: 'The Carter Center  (1982)'
logo: image-1713224369.png
website: 'https://www.cartercenter.org'
description: 'The Carter Center was founded in 1982 by former US President Jimmy Carter and former First Lady Rosalynn Carter to promote democracy. Today, the charity works globally to support democratic elections and strengthen participatory democracy, consistent with human rights.'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713224419
blueprint: partner
