title: 'The Nature Conservancy  (1951)'
logo: oip.pl3fiffjchfv2jbsds2haqhaha.jpeg
website: www.preserve.nature.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1711310051
blueprint: partner
description: |-
  Our Window of Opportunity Is Open Now

  Our planet faces the interconnected crises of rapid climate change and biodiversity loss. We have years, not decades, to address these existential threats.

  The science is clear: We must act now to halt catastrophic climate change and biodiversity loss. What we do between now and 2030 will determine whether we slow warming to 1.5 degrees Celsius  --  the level scientists agree will avoid the worst impacts of climate change.

  Our actions will also determine whether we conserve enough land and water to slow the rapid acceleration of species loss. If we do both, we will safeguard people from the disastrous effects of these crises.

  So much can occur in a single lifetime. Three quarters of the carbon dioxide emissions driven by humans have occurred since 1950. We have seen a nearly 70% average decline of birds, amphibians, mammals, fish and reptiles since just 1970.

  There is no time for delay. Here are The Nature Conservancy’s Goals for 2030. Our approach reflects decades of learning and refining, and the special role TNC can play side-by-side with partners, communities and decision-makers across the globe:
  ]
  CARBON EMISSIONS
  Reduce or store 3 gigatons of CO2 emissions yearly
  We will use the power of nature and the strength of policy and markets to reduce emissions, support renewable energy, and store carbon to reach our goal of avoiding or sequestering 3 billion metric tons of carbon dioxide emissions each year.

  HELPING PEOPLE
  Benefit 100 million people
  We will help 100 million people at severe risk of climate-related emergencies by protecting and restoring the health of natural habitats—from mangroves and reefs to floodplains and forests—that help protect communities from storm surge, extreme rainfall, severe wildfires and sea level rise.

  OUR OCEAN
  Conserve nearly 10 billion acres of ocean
  We will conserve 4 billion hectares (9.9 billion acres) of ocean through new and better-managed protected areas, global-scale sustainable fishing, innovative financing, and positive policy changes to how the world governs the seas.

  HEALTHY LANDS
  Conserve 1.6 billion acres of land
  We will partner with communities around the globe to conserve 650 million hectares (about 1.6 billion acres) of land. Together we will restore and improve management of working lands, support the leadership of Indigenous Peoples as land stewards, and conserve critical forests, grasslands and other habitats rich in carbon and biodiversity.

  FRESHWATER
  Conserve more than 620,000 miles of rivers
  We will conserve 1 million kilometers (621,000 miles) of river systems and 30 million hectares (74 million acres) of lakes and wetlands by engaging in collaborative partnerships, promoting innovative solutions, and supporting policies that improve the quality and amount of water available in freshwater ecosystems and to communities.

  LOCAL LEADERS
  Support 45 million local stewards
  We support 45 million people whose well-being and livelihoods depend on healthy oceans, freshwater, and lands. We will partner with Indigenous People and other local communities to learn from and support their leadership in stewarding their environment, securing rights to resources, improving economic opportunities, and shaping their future.