title: 'The Carter Center  (1982)'
logo: image-1713224369.png
website: 'https://www.cartercenter.org'
description: |-
  The Carter Center
  Waging Peace. Fighting Disease. Building Hope. 

  A not-for-profit, nongovernmental organization, The Carter Center has helped to improve life for people in over 80 countries by resolving conflicts; advancing democracy, human rights, and economic opportunity; preventing diseases; and improving mental health care. The Carter Center was founded in 1982 by former U.S. President Jimmy Carter and former First Lady Rosalynn Carter, in partnership with Emory University, to advance peace and health worldwide.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713226499
blueprint: partner
