title: 'The Nature Conservancy  (1951)'
logo: oip.pl3fiffjchfv2jbsds2haqhaha.jpeg
website: www.preserve.nature.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713373986
blueprint: partner
description: |-
  Here are The Nature Conservancy’s Goals for 2030. Our approach reflects decades of learning and refining, and the special role TNC can play side-by-side with partners, communities and decision-makers across the globe:

  CARBON EMISSIONS
  Reduce or store 3 gigatons of CO2 emissions yearly

  HELPING PEOPLE
  Benefit 100 million people

  OUR OCEAN
  Conserve nearly 10 billion acres of ocean

  HEALTHY LANDS
  Conserve 1.6 billion acres of land
  \
  FRESHWATER
  Conserve more than 620,000 miles of rivers

  LOCAL LEADERS
  Support 45 million local stewards