title: 'TreeSisters  (2009)'
logo: oip.pbdz6lircdue0jtsxtvegwaaaa.jpeg
website: 'https://www.treesisters.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729899
blueprint: partner
description: |-
  Women live with, relate to and use forests differently from men. They should, therefore, be central players in the movement to protect and restore global forests. The fact they are not is unjust. But above all, it undermines the restoration and protection of forests - gender injustice is bad for forests.
  ​
  Gender equity is a pillar in all of our work. Our work in Uganda, Bolivia and the Democratic Republic of Congo is already tackling the twin challenges of deforestation and gender inequality. But we need to do much more, and soon. 

  Women in forest communities have an important relationship and role within land and forests. There is growing evidence that by supporting women in reforestation, we will see more sustainable outcomes both for women and the forests they inhabit. Yet access to resources and legal rights for land are often inequitable.
   
  We will support gender equity by championing women foresters and supporting the community in identifying gender-based issues in the reforestation sector.