title: 'TreeSisters  (  )'
logo: oip.pbdz6lircdue0jtsxtvegwaaaa.jpeg
website: www.treesisters.org
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709860333
blueprint: partner
description: |-
  Gender Equity & Women's Empowerment.
  Women in forest communities have an important relationship and role within land and forests. There is growing evidence that by supporting women in reforestation, we will see more sustainable outcomes both for women and the forests they inhabit. Yet access to resources and legal rights for land are often inequitable.
   
  We will support gender equity by championing women foresters and supporting the community in identifying gender-based issues in the reforestation sector.