title: 'War Child'
logo: image-1709064721.jpeg
website: 'https://www.warchild.net'
description: |-
  The first charities bearing the War Child name were founded in the UK in 1993, and the Netherlands in 1995. Since then, both organisations - joined more recently by new War Childs in Germany, Sweden and the US (where it is known as Children in Conflict) - have worked closely together, but run their own child support programmes.

  Over 30 years, millions of children have been helped through these programmes. However, the same period has seen the number of children living in conflict zones around the world more than double. Child rights continue to be violated at an alarming scale. New approaches and innovations are urgently required. Cue the War Child Alliance.

  The War Child Alliance

  The War Child Alliance brings together the five War Child fundraising members (in the Netherlands, UK, Germany and Sweden, plus Children in Conflict in the US), with 14 programme members, based in and around conflict-affected areas across the world and coordinated by a new international body: the War Child Alliance Foundation.

  Through the Alliance we are integrating our programme activities under one umbrella - allowing us to combine strengths and pool resources - all with the aim to multiply our impact for conflict-affected children.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709489931
blueprint: partner
