title: 'War Child Aliance Foundation (1993)'
logo: image-1709839225.png
website: 'https://www.warchild.net'
description: |-
  We believe no child should be part of war. Ever. And we won’t stop until this belief becomes a reality. We are War Child

  Around the world, hundreds of millions of children are living with the effects of war and conflict. Separated from their homes, schools and loved ones, many are overwhelmed by manifestations of distress.

  We may never be able to take away all the pain that comes with war. But we can create space where children can heal. Through our creative and evidence-based approach, we work exclusively to enhance the innate resilience of children and their communities.

  We are a rights-based organisation  --  which means we also advocate with and on behalf of children to ensure their fundamental rights are upheld.

  Children’s right to learn; to food, water, a safe place to rest their head at night, are all inextricably linked to their right to mental health. We remind governments and other influential actors of the scope of their commitments.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713374955
blueprint: partner
