title: 'Wild Impact (1992)'
logo: cropped-af-logo-website-02-300x134.png
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729630
blueprint: partner
website: 'https://wildimpact.earth'
description: |-
  Africa Foundation has gone global
  Our name change from Africa Foundation to Wild Impact as of July 2024 marks our expansion beyond Africa, to Asia and South America, enabling us to grow and deepen our global impact in partnership with &Beyond.
  While our brand is changing, our trusted methodology will continue to anchor our work and inform all our impact activities.
  Wild Impact underlines our shared impact purpose: to work collaboratively with our partner communities and key stakeholders to conserve the landscapes and seascapes in which we operate for generations to come.