title: 'Wild Impact (1992)'
logo: cropped-af-logo-website-02-300x134.png
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727730791
blueprint: partner
website: 'https://wildimpact.earth'
description: |-
  *     Africa Foundation has gone global
  Our name change from Africa Foundation to Wild Impact as of July 2024 marks our expansion beyond Africa, to Asia and South America, enabling us to grow and deepen our global impact in partnership with &Beyond.
  While our brand is changing, our trusted methodology will continue to anchor our work and inform all our impact activities.
  Wild Impact underlines our shared impact purpose: to work collaboratively with our partner communities and key stakeholders to conserve the landscapes and seascapes in which we operate for generations to come.
  Nurturing, restoring and protecting our natural wild systems, by empowering the communities that are the custodians of these systems. By partnering with communities, governments and the private sector, Wild Impact seeks to achieve a symbiotic balance between land, wildlife and people. We focus on 4 complimentary focal areas that support our sustainable development and enhances our community partnerships.