title: 'Woods Hole Oceanographic Institution  (1930)'
logo: image-1710055104.jpeg
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729674
blueprint: partner
website: 'https://www.whoi.edu'
description: |-
  OUR OCEAN. OUR PLANET. OUR FUTURE.®

  Woods Hole Oceanographic Institution (WHOI) is the world's premier independent organization dedicated exclusively to ocean research, technology, and education. We combine state-of-the-art science, engineering, and ship operations to unravel the mysteries of the deep and devise science-based solutions to planet-wide problems.

  OUR WORK
  WHOI is at the forefront of groundbreaking science and technology development, unlocking the mysteries of our ocean, its connections to life on Earth, and solutions it may hold to some of our most pressing environmental challenges.

  RESEARCH
  Our scientists and engineers lead more than 800 concurrent projects, tackling some of the most challenging and important problems of our time, from climate change and ocean pollution to sustainable food and energy production.

  EXPLORATION
  We operate a fleet of research vessels and vehicles, including two large ships (R/V Neil Armstrong and R/V Atlantis), a smaller coastal research vessel, the iconic human-occupied submersible Alvin, and dozens of other underwater robots.

  EDUCATION
  Through our higher education programs, including the prestigious MIT-WHOI Joint Program, we train new generations of ocean scientists, engineers, and leaders-providing access to cutting edge facilities and unparalleled access to the sea.

  CONNECTION
  WHOI plays a leading role in ocean communications, sharing our insights and knowledge about the ocean to the general public, policymakers, educators, and more, so we can make wise decisions about our ocean, our planet, and our future.