title: 'World Vision  (1950)'
logo: image-1709839436.jpeg
website: 'https://www.worldvision.org'
description: |-
  Dangerously soft-hearted. But just the right kind of dangerous.

  That's because we're a global Christian humanitarian organization. We partner with children, families, and their communities to reach their full potential by tackling the causes of poverty and injustice.

  World Vision is an international partnership of Christians whose mission is to follow our Lord and Savior Jesus Christ in working with the poor and oppressed to promote human transformation, seek justice, and bear witness to the good news of the Kingdom of God.

  We pursue this mission through integrated, holistic commitment to:

      *   Transformational development that is community-based and sustainable, focused especially on the needs of children.
      *    Emergency relief that assists people afflicted by conflict or disaster.
      *    Promotion of justice that seeks to change unjust structures affecting the poor among whom we work.
      *    Partnerships with churches to contribute to spiritual and social transformation.
      *    Public awareness that leads to informed understanding, giving, involvement, and prayer.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1727729833
blueprint: partner
