title: 'World Central Kitchen  (2010)'
logo: image-1713651442.png
website: www.wck.org
description: |-
  World Central Kitchen is first to the frontlines, providing fresh meals in response to humanitarian, climate, and community crises.

  Not only is a thoughtful, freshly prepared meal one less thing someone has to worry about in the wake of a disaster, it is a reminder that you are not alone, that someone cares. Food has the power to be the nourishment and hope we need to carry on in the darkest times. 

  In 2010, Chef José Andrés, ready to use his culinary knowledge and talent to help, headed to Haiti following a devastating earthquake. Cooking alongside displaced families in a camp, he was guided on the proper way to cook black beans the way Haitians like to eat them: mashed and sieved into a creamy sauce. It wasn’t just about feeding people in need  --  it was about listening, learning, and cooking side by side with the people impacted by the crisis. This is the real meaning of comfort food, and it’s the core value that José, along with his wife Patricia, used at the center of founding World Central Kitchen.
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713651465
blueprint: partner
