title: 'World Wildlife Fund  (1961)'
logo: logo.png
website: 'https://www.panda.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1711237748
blueprint: partner
description: |-
  WWF mission statement:

  "We bear witness to the accelerating decline of nature and our climate, with serious consequences for life on Earth, including our own.

  "Our vision is to build a future in which people live in harmony with nature. To deliver this mission, we work to conserve and restore biodiversity, the web that supports all life on Earth; to reduce humanity's environmental footprint; and to ensure the sustainable use of natural resources to support current and future generations.

  "We celebrate and respect diversity in nature and among the people, partners, and communities with whom we work. Across the many cultures and individuals that represent WWF, we are unified by one mission, one brand, and one common set of values:

      "Courage: We demonstrate courage through our actions, we work for change where it's needed, and we inspire people and institutions to tackle the greatest threats to nature and the future of the planet, which is our home.

      "Integrity: We live the principles we call on others to meet. We act with integrity, accountability and transparency, and we rely on facts and science to guide us and to ensure we learn and evolve.

      "Respect: We honor the voices and knowledge of the people and communities that we serve, and we work to secure their rights to a sustainable future.

      "Collaboration: We deliver impact at the scale of the challenges we face through the power of collective action and innovation."

  Active in nearly 100 countries
  6+ million supporters
  30+ million followers on social media