title: 'World Learning  (1932)'
logo: image-1713225048.png
website: 'https://www.worldlearninginc.org'
description: 'World Learning was founded in 1932 by Donald B. Watt to address critical global issues by creating emerging leaders using education, international development, and exchange programs. Today, the charity works to promote civic engagement and strengthen institutions that form the backbone of a democratic society.'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1713225704
blueprint: partner
