title: '*** World Wildlife Fund'
logo: logo.png
website: 'https://www.panda.org'
updated_by: 46c097c5-771c-49e2-b8c6-ba6009ae7172
updated_at: 1709082822
blueprint: partner
description: |-
  We bear witness to the accelerating decline of nature and our climate, with serious consequences for life on Earth, including our own.

  Our vision is to build a future in which people live in harmony with nature. To deliver this mission, we work to conserve and restore biodiversity, the web that supports all life on Earth; to reduce humanity's environmental footprint; and to ensure the sustainable use of natural resources to support current and future generations.

  We celebrate and respect diversity in nature and among the people, partners, and communities with whom we work. Across the many cultures and individuals that represent WWF, we are unified by one mission, one brand, and one common set of values:

  Courage: We demonstrate courage through our actions, we work for change where it's needed, and we inspire people and institutions to tackle the greatest threats to nature and the future of the planet, which is our home.
  Integrity: We live the principles we call on others to meet. We act with integrity, accountability and transparency, and we rely on facts and science to guide us and to ensure we learn and evolve.
  Respect: We honor the voices and knowledge of the people and communities that we serve, and we work to secure their rights to a sustainable future.
  Collaboration: We deliver impact at the scale of the challenges we face through the power of collective action and innovation.
  Ethics

  WWF is committed to a culture which allows people to safely raise concerns of inappropriate conduct by employees of WWF, its partners, and people associated with WWF, without fear of reprisals. Likewise, local communities or individuals from those communities who believe they are negatively impacted by WWF’s activities are welcome to send their concerns. Complaints may be submitted in the complainant’s native language, to the local WWF office or to our EthicsPoint reporting line.

  Commitment to Integrity and Good Conduct

  WWF commits to the highest standards of professionalism, integrity and ethics in our workplace and in our activities. These commitments are fundamental to creating effective, lasting and equitable solutions to today’s environmental challenges.

  The full commitments are available here.

  Commitment to Independence

  World Wildlife Fund, Inc. (WWF-US) is a U.S. public charity whose mission is to leverage sound science to conserve nature and reduce the most pressing threats to the diversity of life on Earth. We are an independent organization overseen by a Board of Directors with expertise in science, conservation, finance, and public policy, who volunteer their time and service.

  All actions, undertakings, and positions of WWF-US are determined by the organization alone. WWF does not operate as an agent or representative for any funder and does not accept funding from any source that could compromise our independence.

  WWF-US undertakes certain limited efforts to influence public policy to save nature, in furtherance of our mission and in accord with all applicable laws and regulations. WWF-US’s advocacy efforts are determined and undertaken independently, represent no party other than ourselves, and are fully disclosed as required.